export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const UPDATE_USER_DATA = "UPDATE_USER_DATA";

export const GET_CLASSES_LIST_START = "GET_CLASSES_LIST_START";
export const GET_CLASSES_LIST_FAIL = "GET_CLASSES_LIST_FAIL";
export const GET_CLASSES_LIST_SUCCESS = "GET_CLASSES_LIST_SUCCESS";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";

export const CREATE_CLASS_START = "CREATE_CLASS_START";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const DELETE_CLASS = "DELETE_CLASS";

export const GET_ANNOUNCEMENT_LIST_START = "GET_ANNOUNCEMENT_LIST_START";
export const GET_ANNOUNCEMENT_LIST_FAIL = "GET_ANNOUNCEMENT_LIST_FAIL";
export const GET_ANNOUNCEMENT_LIST_SUCCESS = "GET_ANNOUNCEMENT_LIST_SUCCESS";


export const CREATE_ANNOUNCEMENT_START = "CREATE_ANNOUNCEMENT_START";
export const CREATE_ANNOUNCEMENT_FAIL = "CREATE_ANNOUNCEMENT_FAIL";
export const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";

export const GET_POSTS_LIST_START = "GET_POSTS_LIST_START";
export const GET_POSTS_LIST_FAIL = "GET_POSTS_LIST_FAIL";
export const GET_POSTS_LIST_SUCCESS = "GET_POSTS_LIST_SUCCESS";
export const GET_COMMENTS_LIST_SUCCESS = 'GET_COMMENTS_LIST_SUCCESS';
export const HANDLE_POSTS_LOGOUT = "HANDLE_POSTS_LOGOUT";


export const CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';

export const JOIN_CLASS_START = "JOIN_CLASS_START";
export const JOIN_CLASS_FAIL = "JOIN_CLASS_FAIL";
export const JOIN_CLASS_SUCCESS = "JOIN_CLASS_SUCCESS";